# Generated by Django 5.1.1 on 2024-09-25 07:42

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='human',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
