# Generated by Django 4.2.16 on 2024-09-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Account USER', 'verbose_name_plural': 'Account USERS'},
        ),
        migrations.RemoveField(
            model_name='human',
            name='age',
        ),
        migrations.AddField(
            model_name='human',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
