# Generated by Django 5.1.1 on 2024-09-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_human_managers'),
        ('account', '0003_alter_human_managers'),
    ]

    operations = [
    ]
