# Generated by Django 5.1.1 on 2024-09-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='ingredients', related_query_name='ingredients', to='product.product'),
        ),
    ]
