# Generated by Django 5.1.1 on 2024-09-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent_alter_productimage_image'),
        ('product', '0002_alter_ingredients_products'),
    ]

    operations = [
    ]
