# Generated by Django 5.1.1 on 2024-09-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_alter_favorite_user'),
        ('product', '0004_alter_ingredients_is_delete_alter_product_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='product.product'),
        ),
    ]
