# Generated by Django 5.1.1 on 2024-09-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_human_managers_alter_human_is_delete'),
        ('favorite', '0003_alter_favorite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', related_query_name='favorites', to='account.human'),
        ),
    ]
