# Generated by Django 5.1.1 on 2024-10-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedComment',
            fields=[
                ('xtdcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments_xtd.xtdcomment')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('submit_date',),
            },
            bases=('django_comments_xtd.xtdcomment',),
        ),
    ]
